from enum import Enum


class FindingCategory(str, Enum):
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    HTTP_METHODS = "HTTP_METHODS"
    SENSITIVE_DATA = "SENSITIVE_DATA"
    VERBOSE_ERRORS = "VERBOSE_ERRORS"
    SECURITY_HEADERS = "SECURITY_HEADERS"
    STATUS_CODES = "STATUS_CODES"
    INFORMATION_DISCLOSURE = "INFORMATION_DISCLOSURE"
